### ISSUE TITLE
Chrome 111.0.5563.64 broke it...

### ISSUE THREAD

**Issue by ik8sqi** [clems71/globalprotect-saml#4]
On a Macbook M1 running MacOS Ventura 13.2.1 :
The last Chrome version I used with which this works is 110.0.5481.177. I updated to Chrome 111.0.5563.64 and now I receive this error below. Reverting to the older Chrome 110.0.5481.177 fixes the problem.

Error with current build of globalprotect-saml:
2023/03/08 03:45:17 prelogin flow failed : websocket.Dial ws://127.0.0.1:49768/devtools/browser/7bb579d8-a0ef-4d2e-b13e-be803977827c: bad status

With a previous build of vpn_arm64_darwin from October 2022 I instead get this error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10043eb60]

goroutine 1 [running]:
main.Prelogin({0x1400016c900?, 0x1400011e190?})
	/Users/macbook/Downloads/globalprotect-saml-main/main.go:80 +0x80
main.main()
	/Users/macbook/Downloads/globalprotect-saml-main/main.go:231 +0xe0

**Comment by clems71** [comment]
Thanks for reporting. It should now be fixed in release r2 : https://github.com/clems71/globalprotect-saml/releases/tag/r2

**Comment by clems71** [comment]
Let me know if this works for you, and I will close the issue accordingly!

**Comment by ik8sqi** [comment]
Wow - you're fast! Worked like a charm, thank you!

FYI - I had commented out the line below in my local copy so I could save the preferences (i.e. store the username/password) in the Chrome window so it'd be pre-populated every time it appeared. Just a personal opinion that keeping the prefs is better than deleting them.

func Prelogin(samlPreloginHTML string) (*SAMLPreloginData, error) {
//	os.RemoveAll("./data/Default/Preferences")


Thanks again, both for sharing the code to begin with, and for the super-fast fix!

Roberto
